### ISSUE TITLE
publish latest successfully tested build via API

### ISSUE THREAD

**Issue by jeremyeder** [openshift/release-controller#70]
The purpose of this API would be to facilitate a way for other systems/projects/products to daisy-chain off of origin/openshift product CI flows, optimizing when and how often these external processes run.

/cc @ethernetdan

**Comment by stevekuznetsov** [comment]
Can you describe here as well which fields you'd like to see / shape of the output payload?

**Comment by ethernetdan** [comment]
@stevekuznetsov Right now thinking of returning [`ReleasePage`](https://github.com/openshift/release-controller/blob/20d10a9/cmd/release-controller/http_helper.go#L18-L21) as JSON. 

Is there any information in it that shouldn't be included / additional information that could be helpful?

**Comment by stevekuznetsov** [comment]
That seems reasonable to me!

**Comment by smarterclayton** [comment]
Folded #72 into #78 (slightly different URL, some lookup fixes).
