### ISSUE TITLE
RFE: make source code discoverable

### ISSUE THREAD

**Issue by ktdreyer** [openshift/release-controller#77]
When I was browsing https://openshift-release.svc.ci.openshift.org , I could not figure out where to read the source or contribute changes to the UX. I was searching repos on GitHub and didn't find this one until Clayton pointed me at it.

It would be great to link to this GitHub repository in the footer of each page, so it's easy for people to find the source code. (For example, https://koji.fedoraproject.org/koji/ has a "Powered by Koji" link in the footer.)

Here's a user story:

_As an external-to-openshift developer,
I want to know the source code location for https://openshift-release.svc.ci.openshift.org,
so that I can understand more about this application, its inputs, and contribute patches_

**Comment by smarterclayton** [comment]
Fixed in #78
